### ISSUE TITLE
Открытие BAS файла. Ошибка!

### ISSUE THREAD

**Issue by DeepLight01** [thetrik/Vector06C-Basic-Converter#1]
Открываю любой BAS файл и вот
![image](https://user-images.githubusercontent.com/12671463/120705923-18477300-c4c1-11eb-9db6-3f75931ee9d0.png)

**Comment by thetrik** [comment]
Пофиксил. Там была путаница в форматах. BAS файл сейчас открывается корректно.

**Comment by DeepLight01** [comment]
Спасибо. Ты VB6 используешь? Под виндой 10? Как устанавливал и запускал?

**Comment by thetrik** [comment]
> Спасибо. Ты VB6 используешь? Под виндой 10? Как устанавливал и запускал?

Да VB6. У меня эта среда установлена под Windows 7. Вроде бы под Win10 тоже ставится должна.

**Comment by DeepLight01** [comment]
Да, теперь работает! Спасибо!

**Comment by DeepLight01** [comment]
В конце листингов только какие-то нули. Так и должно быть?
![image](https://user-images.githubusercontent.com/12671463/120717703-ad9e3380-c4d0-11eb-878a-3eb432ef469b.png)

**Comment by thetrik** [comment]
> В конце листингов только какие-то нули. Так и должно быть?
> ![image](https://user-images.githubusercontent.com/12671463/120717703-ad9e3380-c4d0-11eb-878a-3eb432ef469b.png)

Исправлено в [версии 1.0.4](https://github.com/thetrik/Vector06C-Basic-Converter/releases/tag/1.0.4). Спасибо за тест!
