### ISSUE TITLE
 Latin letter 'A'.

### ISSUE THREAD

**Issue by derFremd** [thetrik/Vector06C-Basic-Converter#2]
Проблема с латинской буквой 'A'. После записи в .CAS файл:
10 REM "CONGRATULATIONS"
получаем
10 REM "CONGRTULTION"

**Comment by thetrik** [comment]
[Fixed in 1.0.6 version](https://github.com/thetrik/Vector06C-Basic-Converter/releases/tag/1.0.6). Thank you for testing!

**Comment by derFremd** [comment]
Для команды REM ошибка исправилось, но для PRINT, к сожалению, осталась.

**Comment by thetrik** [comment]
> Для команды REM ошибка исправилось, но для PRINT, к сожалению, осталась.

Пофиксил баг, чекни пожалуйста.
